INSERT INTO `online_store`.`category` (`id`, `category_name`) VALUES ('1', "Men\'s Wear");
INSERT INTO `online_store`.`category` (`id`, `category_name`) VALUES ('2', "Women\'s Wear");
INSERT INTO `online_store`.`category` (`id`, `category_name`) VALUES ('3', "Watches");
INSERT INTO `online_store`.`category` (`id`, `category_name`) VALUES ('4', "Shoes");

INSERT INTO `online_store`.`product` (`id`, `product_name`, `price`, `rating`, `size`) VALUES ('1', "Men\'s Adidas shoe", '3500', '4', 'Small');
INSERT INTO `online_store`.`product` (`id`, `product_name`, `price`, `rating`, `size`) VALUES ('2', "Men\'s Nike shoe", '4000', '5', 'Medium');
INSERT INTO `online_store`.`product` (`id`, `product_name`, `price`, `rating`, `size`) VALUES ('3', "Women\'s Adidass shoe", '3800', '4', 'Large');
INSERT INTO `online_store`.`product` (`id`, `product_name`, `price`, `rating`, `size`) VALUES ('4', "Ladies\' watch", '1200', '4', 'Small');
INSERT INTO `online_store`.`product` (`id`, `product_name`, `price`, `rating`, `size`) VALUES ('5', "Gents\' watch", '1350', '3', 'Small');
INSERT INTO `online_store`.`product` (`id`, `product_name`, `price`, `rating`, `size`) VALUES ('6', "Unisex watch", '1000', '5', 'Large');
INSERT INTO `online_store`.`product` (`id`, `product_name`, `price`, `rating`, `size`) VALUES ('7', "Men\'s T-shirt", '1250', '4', 'Medium');
INSERT INTO `online_store`.`product` (`id`, `product_name`, `price`, `rating`, `size`) VALUES ('8', "Men\'s Trouser", '2400', '3', 'Small');
INSERT INTO `online_store`.`product` (`id`, `product_name`, `price`, `rating`, `size`) VALUES ('9', "Women\'s Blouse", '1600', '4', 'Large');
INSERT INTO `online_store`.`product` (`id`, `product_name`, `price`, `rating`, `size`) VALUES ('10', "Women\'s Skirt", '1750', '5', 'Medium');

INSERT INTO `online_store`.`product_category` (`product_id`, `category_id`) VALUES ('1', '1');
INSERT INTO `online_store`.`product_category` (`product_id`, `category_id`) VALUES ('1', '4');
INSERT INTO `online_store`.`product_category` (`product_id`, `category_id`) VALUES ('2', '1');
INSERT INTO `online_store`.`product_category` (`product_id`, `category_id`) VALUES ('2', '4');
INSERT INTO `online_store`.`product_category` (`product_id`, `category_id`) VALUES ('3', '2');
INSERT INTO `online_store`.`product_category` (`product_id`, `category_id`) VALUES ('3', '4');
INSERT INTO `online_store`.`product_category` (`product_id`, `category_id`) VALUES ('4', '2');
INSERT INTO `online_store`.`product_category` (`product_id`, `category_id`) VALUES ('4', '3');
INSERT INTO `online_store`.`product_category` (`product_id`, `category_id`) VALUES ('5', '1');
INSERT INTO `online_store`.`product_category` (`product_id`, `category_id`) VALUES ('5', '3');
INSERT INTO `online_store`.`product_category` (`product_id`, `category_id`) VALUES ('6', '1');
INSERT INTO `online_store`.`product_category` (`product_id`, `category_id`) VALUES ('6', '2');
INSERT INTO `online_store`.`product_category` (`product_id`, `category_id`) VALUES ('6', '3');
INSERT INTO `online_store`.`product_category` (`product_id`, `category_id`) VALUES ('7', '1');
INSERT INTO `online_store`.`product_category` (`product_id`, `category_id`) VALUES ('8', '1');
INSERT INTO `online_store`.`product_category` (`product_id`, `category_id`) VALUES ('9', '2');
INSERT INTO `online_store`.`product_category` (`product_id`, `category_id`) VALUES ('10', '2');

INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('1', '1', 'jpg', '/assets/images/product/1');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('2', '2', 'jpg', '/assets/images/product/1');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('3', '3', 'jpg', '/assets/images/product/1');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('4', '1', 'jpg', '/assets/images/product/2');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('5', '2', 'jpg', '/assets/images/product/2');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('6', '3', 'jpg', '/assets/images/product/2');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('7', '1', 'jpg', '/assets/images/product/3');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('8', '2', 'jpg', '/assets/images/product/3');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('9', '3', 'jpg', '/assets/images/product/3');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('10', '1', 'jpg', '/assets/images/product/4');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('11', '2', 'jpg', '/assets/images/product/4');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('12', '3', 'jpg', '/assets/images/product/4');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('13', '1', 'jpg', '/assets/images/product/5');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('14', '2', 'jpg', '/assets/images/product/5');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('15', '3', 'jpg', '/assets/images/product/5');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('16', '1', 'jpg', '/assets/images/product/6');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('17', '2', 'jpg', '/assets/images/product/6');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('18', '3', 'jpg', '/assets/images/product/6');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('19', '1', 'jpg', '/assets/images/product/7');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('20', '2', 'jpg', '/assets/images/product/7');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('21', '3', 'jpg', '/assets/images/product/7');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('22', '1', 'jpg', '/assets/images/product/8');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('23', '2', 'jpg', '/assets/images/product/8');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('24', '3', 'jpg', '/assets/images/product/8');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('25', '1', 'jpg', '/assets/images/product/9');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('26', '2', 'jpg', '/assets/images/product/9');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('27', '3', 'jpg', '/assets/images/product/9');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('28', '1', 'jpg', '/assets/images/product/10');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('29', '2', 'jpg', '/assets/images/product/10');
INSERT INTO `online_store`.`image` (`id`, `image_name`, `extension`, `image_location`) VALUES ('30', '3', 'jpg', '/assets/images/product/10');

INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('1', '1');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('1', '2');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('1', '3');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('2', '4');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('2', '5');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('2', '6');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('3', '7');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('3', '8');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('3', '9');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('4', '10');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('4', '11');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('4', '12');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('5', '13');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('5', '14');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('5', '15');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('6', '16');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('6', '17');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('6', '18');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('7', '19');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('7', '20');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('7', '21');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('8', '22');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('8', '23');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('8', '24');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('9', '25');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('9', '26');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('9', '27');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('10', '28');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('10', '29');
INSERT INTO `online_store`.`product_image` (`product_id`, `image_id`) VALUES ('10', '30');